-- Batch ETL Pipeline
-- Snowflake database and schemas

CREATE DATABASE IF NOT EXISTS BATCH_ETL_DB;

USE DATABASE BATCH_ETL_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS CURATED;
